name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: autopep8
      uses: peter-evans/autopep8@v1.1.0
      with:
        args: --recursive --in-place --aggressive --aggressive .
